**Data Exploration**

In [1]:
#importing dependencies

try:
    import pandas as pd
except ModuleNotFoundError:
    import sys
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"])
    import pandas as pd

#mysql toolkit
try:
    import pymysql
    from sqlalchemy import create_engine
except ModuleNotFoundError:
    import subprocess
    import sys

    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "PyMySQL", "SQLAlchemy"]
    )
    import pymysql
    from sqlalchemy import create_engine

In [2]:
df=pd.read_csv("apple_global_sales_dataset.csv", encoding_errors='ignore')
df.shape

(11500, 27)

In [3]:
df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,...,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,...,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,...,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,...,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,...,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 11500 non-null  str
 1   sale_date               11500 non-null  str
 2   year                    11500 non-null  int64
 3   quarter                 11500 non-null  str
 4   month                   11500 non-null  str
 5   country                 11500 non-null  str
 6   region                  11500 non-null  str
 7   city                    11500 non-null  str
 8   product_name            11500 non-null  str
 9   category                11500 non-null  str
 10  storage                 6696 non-null   str
 11  color                   11500 non-null  str
 12  unit_price_usd          11500 non-null  float64
 13  discount_pct            11500 non-null  int64
 14  units_sold              11500 non-null  int64
 15  discounted_price_usd    11500 non-null  float64
 16  revenue_usd             11500 non-null  float64
 17  currency                11500 non-null  str
 18  fx_rate_to_usd          11500 non-null  float64
 19  revenue_local_currency  11500 non-null  float64
 20  sales_channel           11500 non-null  str
 21  payment_method          11500 non-null  str
 22  customer_segment        11500 non-null  str
 23  customer_age_group      11500 non-null  str
 24  previous_device_os      3444 non-null   str
 25  customer_rating         8140 non-null   float64
 26  return_status           11500 non-null  str
dtypes: float64(6), int64(3), str(18)
memory usage: 2.4 MB

In [5]:
# all duplicates 
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

sale_id                      0
sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   4804
color                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        8056
customer_rating           3360
return_status                0
dtype: int64

In [7]:
df['previous_device_os'].value_counts(dropna=False)

previous_device_os
NaN         8056
Android      595
iOS 16       587
Other        581
New User     571
iOS 15       556
iOS 17       554
Name: count, dtype: int64

In [8]:
df['customer_rating'].value_counts(dropna=False)

customer_rating
NaN    3360
4.0     434
4.4     433
4.6     433
3.7     432
3.2     428
4.2     426
3.4     422
4.8     414
4.3     413
3.5     407
4.1     405
3.6     399
3.9     399
3.3     398
4.7     394
4.9     393
3.8     376
3.1     373
4.5     366
3.0     198
5.0     197
Name: count, dtype: int64

**Cleaning Data**

In [9]:
# Standardize columns

text_cols = ['country', 'region', 'city', 'product_name', 'category', 
             'color', 'sales_channel', 'payment_method', 'customer_segment',
             'customer_age_group', 'previous_device_os', 'return_status']
for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [10]:
# Add a new column for discount amount
df['discount_amount_usd'] = ((df['unit_price_usd'] - df['discounted_price_usd']) * df['units_sold']).round(2)

# Add new column for revenue without discount
df['revenue_no_discount_usd'] = (df['unit_price_usd'] * df['units_sold']).round(2)

In [11]:
# Rename column for clarity
df = df.rename(columns={
    'revenue_usd': 'revenue_discounted_usd',
    'revenue_local_currency' : 'revenue_discounted_local_currency'
})

In [12]:
df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,revenue_discounted_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status,discount_amount_usd,revenue_no_discount_usd
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,Airpods (3Rd Gen),Airpods,...,134344.84,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept,11.15,159.27
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,Usb-C Woven Charge Cable,Accessories,...,115597.15,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept,22.50,149.95
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,...,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept,0.00,1175.68
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,Macbook Pro 14-Inch (M3),Mac,...,3506044.78,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept,0.00,3865.54
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,...,1952780.07,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept,113.31,2266.32

In [17]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_discounted_usd', 'currency', 'fx_rate_to_usd',
       'revenue_discounted_local_currency', 'sales_channel', 'payment_method',
       'customer_segment', 'customer_age_group', 'previous_device_os',
       'customer_rating', 'return_status', 'discount_amount_usd',
       'revenue_no_discount_usd'],
      dtype='str')

In [18]:
# Save cleaned data
df.to_csv('apple_sales_cleaned.csv', index=False)
print(f"\nCleaned shape: {df.shape}")
print("\nCleaned data saved!")

Cleaned shape: (11500, 29)

Cleaned data saved!

In [ ]:
# Replace YOUR_PASSWORD with your local MySQL root password
engine_mysql = create_engine("mysql+pymysql://root:YOUR_PASSWORD@localhost/apple_db")

try: 
    engine_mysql
    print("Connection to MySQL database established successfully!")
except:
    print("Unable to connect")

Connection to MySQL database established successfully!

In [20]:
df.to_sql(name='apple', con=engine_mysql, if_exists='append', index=False)

11500